### ISSUE TITLE
BYG Boat Support for Banner Features

### ISSUE THREAD

**Issue by ardissaps** [KxmischesDomi/MoreBannerFeatures#19] opened 2022-07-12 09:08 UTC
Would you please make compatibility with these mods? Thank you very much (1.18.2)

[Oh BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) :
![image](https://user-images.githubusercontent.com/82106625/178454214-51e743eb-1620-4529-9983-0ccde81ae70f.png)

[Charm](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) :
![image](https://user-images.githubusercontent.com/82106625/178454724-226a347f-0f61-4eee-a1fa-b100856589a6.png)

Also for Boat Container :
https://github.com/KxmischesDomi/BoatContainer/issues/28

**Comment by DomiIRL** [comment] 2022-07-18 19:27
Duplicate of https://github.com/KxmischesDomi/MoreBannerFeatures/issues/18

**Closed as completed by DomiIRL** 2022-07-18 19:27 UTC
Labels: duplicate

**Comment by ardissaps** [comment] 2022-07-19 01:49
Sorry the duplicate was caused by my slowass internet. :p
